print("Input first number") 
num1 = int(input()) 
print("Input second number") 
num2 = int(input()) 
print("product of the two numbers is",num1*num2) 
print("division of the two numbers is",num1/num2) 
